const PREVIEW_MENU_KEY="quppa-admin-preview-menu";
const $=id=>document.getElementById(id);
const LANGS=["tr","en","ru","ar"];
let menu=[], activeCat=0, activeProduct=0;
function setStatus(msg,type="info"){$("status").textContent=msg;$("status").dataset.type=type}
function obj(v=""){return{tr:v,en:v,ru:v,ar:v}}
function ensureLang(o){if(!o||typeof o!=="object")return obj(String(o||""));LANGS.forEach(l=>o[l]??="");return o}
function slug(s){return String(s||"urun").toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"urun"}
function currentCat(){return menu[activeCat]} function currentProduct(){return currentCat()?.products?.[activeProduct]}
function normalizeMenu(raw){if(!Array.isArray(raw))throw new Error("menu.json dizi formatında olmalı.");return raw.map((cat,i)=>({id:cat.id||`category-${i+1}`,icon:cat.icon||"fa-utensils",name:ensureLang(cat.name||obj(cat.id||`Kategori ${i+1}`)),desc:ensureLang(cat.desc||obj("")),products:Array.isArray(cat.products)?cat.products.map((p,j)=>normalizeProduct(p,cat.id||`category-${i+1}`,j)):[]}))}
function normalizeProduct(p,catId,j){const id=p.id||`${catId}-${j+1}`;return{id,name:ensureLang(p.name||obj(id)),desc:ensureLang(p.desc||obj("")),detail:ensureLang(p.detail||p.desc||obj("")),badge:ensureLang(p.badge||obj("")),price:Number(p.price)||0,image:p.image||"",localImage:p.localImage||`${catId}/${id}.webp`,tags:Array.isArray(p.tags)?p.tags:[],icons:Array.isArray(p.icons)?p.icons:[],isAvailable:p.isAvailable!==false,isFeatured:!!p.isFeatured,isSignature:!!p.isSignature}}
async function loadCurrent(){try{const res=await fetch("./menu.json?admin="+Date.now(),{cache:"no-cache"});if(!res.ok)throw new Error("menu.json yüklenemedi: "+res.status);menu=normalizeMenu(await res.json());activeCat=0;activeProduct=0;renderAll();setStatus("Mevcut menu.json yüklendi.","ok")}catch(e){setStatus(e.message,"error")}}
function renderAll(){renderCategories();renderProducts();renderEditor();validate()}
function renderCategories(){$("categoryList").innerHTML=menu.map((c,i)=>`<button class="catItem ${i===activeCat?"active":""}" data-cat="${i}"><span><b>${c.name.tr||c.id}</b><small>${c.products.length} ürün · ${c.id}</small></span><span>›</span></button>`).join("");document.querySelectorAll("[data-cat]").forEach(b=>b.onclick=()=>{activeCat=Number(b.dataset.cat);activeProduct=0;renderAll()})}
function renderProducts(){const cat=currentCat();$("currentCategoryTitle").textContent=cat?cat.name.tr:"Ürünler";$("currentCategoryMeta").textContent=cat?`${cat.id} · ${cat.products.length} ürün`:"Kategori seçilmedi";$("productList").innerHTML=cat?cat.products.map((p,i)=>`<button class="productCard ${i===activeProduct?"active":""}" data-product="${i}"><b>${p.name.tr||p.id}</b><span>${p.desc.tr||""}</span><div class="meta"><span>${p.price} ₺</span><span class="pill">${p.isAvailable?"Aktif":"Pasif"}</span></div></button>`).join(""):"";document.querySelectorAll("[data-product]").forEach(b=>b.onclick=()=>{activeProduct=Number(b.dataset.product);renderEditor();renderProducts()})}
function fillLang(prefix,objv){LANGS.forEach(l=>$(prefix+"_"+l).value=(objv&&objv[l])||"")} function readLang(prefix){const o={};LANGS.forEach(l=>o[l]=$(prefix+"_"+l).value.trim());return o}
function renderEditor(){const p=currentProduct(),form=$("editorForm");if(!p){form.classList.add("hidden");return}form.classList.remove("hidden");$("editorTitle").textContent=p.name.tr||p.id;$("p_id").value=p.id;$("p_price").value=p.price;$("p_image").value=p.image||"";$("p_localImage").value=p.localImage||"";fillLang("p_name",p.name);fillLang("p_desc",p.desc);fillLang("p_badge",p.badge);$("p_tags").value=(p.tags||[]).join(", ");$("p_icons").value=(p.icons||[]).join(", ");$("p_available").checked=p.isAvailable!==false;$("p_featured").checked=!!p.isFeatured;$("p_signature").checked=!!p.isSignature}
function saveProduct(){const p=currentProduct();if(!p)return;p.id=slug($("p_id").value);p.price=Number($("p_price").value)||0;p.image=$("p_image").value.trim();p.localImage=$("p_localImage").value.trim();p.name=readLang("p_name");p.desc=readLang("p_desc");p.detail={...p.desc};p.badge=readLang("p_badge");p.tags=$("p_tags").value.split(",").map(x=>x.trim()).filter(Boolean);p.icons=$("p_icons").value.split(",").map(x=>x.trim()).filter(Boolean);p.isAvailable=$("p_available").checked;p.isFeatured=$("p_featured").checked;p.isSignature=$("p_signature").checked;renderAll();setStatus("Ürün kaydedildi.","ok")}
function addProduct(){const c=currentCat();if(!c)return;const id=`${c.id}-new-${Date.now().toString().slice(-4)}`;c.products.push(normalizeProduct({id,name:obj("Yeni Ürün"),price:0,isAvailable:true},c.id,c.products.length));activeProduct=c.products.length-1;renderAll()}
function duplicateProduct(){const c=currentCat(),p=currentProduct();if(!c||!p)return;const copy=JSON.parse(JSON.stringify(p));copy.id=slug(copy.id+"-copy");copy.name.tr=(copy.name.tr||copy.id)+" Kopya";c.products.splice(activeProduct+1,0,copy);activeProduct++;renderAll()}
function deleteProduct(){const c=currentCat();if(!c)return;if(!confirm("Ürünü silmek istiyor musun?"))return;c.products.splice(activeProduct,1);activeProduct=Math.max(0,activeProduct-1);renderAll()}
function addCategory(){const id=`category-${Date.now().toString().slice(-4)}`;menu.push({id,icon:"fa-utensils",name:obj("Yeni Kategori"),desc:obj(""),products:[]});activeCat=menu.length-1;activeProduct=0;renderAll()}
function validate(){const warnings=[],ids=new Set();menu.forEach(c=>{if(!c.id)warnings.push("Kategori ID eksik.");(c.products||[]).forEach(p=>{if(ids.has(p.id))warnings.push("Tekrarlanan ürün ID: "+p.id);ids.add(p.id);if(!p.name.tr)warnings.push("TR ürün adı eksik: "+p.id);if(!Number.isFinite(Number(p.price)))warnings.push("Fiyat geçersiz: "+p.id)})});$("validation").innerHTML=warnings.length?warnings.slice(0,8).map(w=>`<div class="warn">${w}</div>`).join(""):`<div class="ok">JSON geçerli görünüyor.</div>`;return warnings}
function download(){validate();const blob=new Blob([JSON.stringify(menu,null,2)+"\n"],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="menu.json";a.click();URL.revokeObjectURL(a.href)}
function preview(){try{localStorage.setItem(PREVIEW_MENU_KEY,JSON.stringify(menu));window.open("./index.html?mode=demo&preview=local","_blank")}catch(e){alert("Preview kaydedilemedi: "+e.message)}}
$("loadCurrentBtn").onclick=loadCurrent;$("fileInput").onchange=async e=>{const f=e.target.files[0];if(!f)return;try{menu=normalizeMenu(JSON.parse(await f.text()));activeCat=0;activeProduct=0;renderAll();setStatus("JSON içe aktarıldı.","ok")}catch(err){setStatus(err.message,"error")}};$("downloadBtn").onclick=download;$("previewBtn").onclick=preview;$("addProductBtn").onclick=addProduct;$("addCategoryBtn").onclick=addCategory;$("deleteProductBtn").onclick=deleteProduct;$("duplicateProductBtn").onclick=duplicateProduct;$("editorForm").onsubmit=e=>{e.preventDefault();saveProduct()};loadCurrent();
